version: "3.9"

services:
  models:
    build: ../models
    volumes:
      - ./models/ollama:/root/.ollama
    ports:
      - "11434:11434"
    gpus: all
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "2024:2024"
    depends_on:
      - models
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
